baseurl = "http://zerobyte.io/"
title = "zerobyte"
languageCode = "en-us"
copyright = "Copyright (c) 2014 - 2017, Philipp Jovanovic; all rights reservered."

[author]
    name = "Philipp Jovanovic"

[permalinks]
    post = "/blog/:year/:month/:day/:title/"

[menu]
[[menu.main]]
    name       = "Home"
    url        = "/"
    identifier = "homeId"
    weight     = 0
[[menu.main]]
    name       = "Blog"
    url        = "/blog/"
    identifier = "blogId"
    weight     = 1
[[menu.main]]
    name       = "Research"
    url        = "/research/"
    identifier = "researchId"
    weight     = 2
[[menu.main]]
    name       = "Talks"
    url        = "/talks/"
    identifier = "talksId"
    weight     = 3
