baseurl = "http://zerobyte.io/"
title = "zerobyte"
languageCode = "en-us"
copyright = "Copyright (c) 2014 - 2017, Philipp Jovanovic; all rights reservered."

[author]
    name = "Philipp Jovanovic"

[permalinks]
    post = "/blog/:year/:month/:day/:title/"
